### ISSUE TITLE
Error when attempting to write bytes to state file openened in text mode

### ISSUE THREAD

**Issue by Woazboat** [iandees/pyosm#11]
The `iter_osm_stream` function fetches the current state using the requests module and then tries to write it to a state file. The data to be written `u.content` is of type `bytes`, but the file is opened in text mode (`w` instead of `wb`) and therefore only accepts strings and not bytes. 
This could be fixed by either using the request content as a string instead of as bytes (`u.text`) or by opening the file in binary mode (`open('%s/state.txt' % state_dir, 'wb')`)

https://github.com/iandees/pyosm/blob/7d0a8886ea98eb5a18e052b14dbcda1786f05da0/pyosm/parsing.py#L282

**Comment by iandees** [comment]
Thanks, I switched to using `.text`.
